config/routes.rb
Rails.application.routes.draw do
  root 'words#index'
  resources :words

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.order("updated_at DESC").page(params[:page]).per(5)
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @title = "単語を登録する｜"
    @word  = Word.new
  end

  def create
    @title = "単語の登録が完了しました｜"
    Word.create(word_params)
    # redirect_to action: :show
  end

  def edit
    @title = "単語を編集する｜"
  end

  def update
  end

  def destroy
  end

  def word_params
    params.require(:word).permit(:word, :text, :category, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %>W o r D r a w e r</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <div class="menu">
    <span style="float:left"><a href="/" id="button">w o r D r a w e r</a></span>
    <!-- <%= link_to "w o r D r a w e r", root_path %> -->
    <span style="float:right"><a href="" id="button">ログアウト</a></span>
    <span style="float:right"><a href="" id="button">ユーザーページ</a></span>
  </div>
  <div class="title">
  <%= image_tag "worDrawer-logo.png" %>
  </div>
</header>
<body>
  <div class="contents">
    <%= yield %>
  </div>
</body>
</html>

app/views/words/_word.html.erb
<% @words.each do |word| %>
  <% if word.status == "1" %>
  <div class="red_1">
    <b>★ <%= word.word %></b>
    <span class="text">｜<%= word.category %><br /><br /><%= word.text %></span>
  </div>
  <% elsif word.status == "2" %>
  <div class="yellow_2">
    <b>★ <%= word.word %></b>
    <span class="text">｜<%= word.category %><br /><br /><%= word.text %></span>
  </div>
  <% elsif word.status == "3" %>
  <div class="blue_3">
    <b>★ <%= word.word %></b>
    <span class="text">｜<%= word.category %><br /><br /><%= word.text %></span>
  </div>
  <% elsif word.status == "4" %>
  <div class="white_4">
    <b>★ <%= word.word %></b>
    <span class="text">｜<%= word.category %><br /><br /><%= word.text %></span>
  </div>
  <% end %>
  <br />
<% end %>
<%= paginate(@words) %>

app/views/words/create.html.erb
<h1>Words#create</h1>

<div class="notification">
  <p>単語の登録が完了しました。</p>
</div>
<!-- <%= render partial: "word", collection: @word %> -->

app/views/words/index.html.erb
<b>Words#index</b><br /><br />
<%= link_to "単語を登録する", new_word_path %>
<br><br>
<% if @words.present? %>
  <%= render partial: "word" %>
  <!-- <%= render partial: "word", collection: @words %> -->
<% else %>
  <p>単語が登録されていません。</p>
<% end %>

app/views/words/new.html.erb
<b>Words#new</b><br /><br />

<%= form_for(@word) do |f| %>
<table class="form">
  <tr>
    <th><%= f.label :word, "単語" %></th>
    <td><%= f.text_field :word %></td>
  </tr>
  <tr>
    <th><%= f.label :text, "説明" %></th>
    <td><%= f.text_area :text, :size => "50x5" %></td>
  </tr>
  <tr>
    <th><%= f.label :category, "カテゴリ" %></th>
    <td><%= f.text_field :category %></td>
  </tr>
  <tr>
    <th><%= f.label :status, "ステータス" %></th>
    <td><%= f.radio_button :status, "1" %>あか
    <%= f.radio_button :status, "2" %>きいろ
    <%= f.radio_button :status, "3" %>あお
    <%= f.radio_button :status, "4" %>しろ</td>
  </tr>
</table><br />
<%= f.submit "単 語 を 登 録 す る" %>
<% end %>

app/views/words/show.html.erb
<h1>Words#show</h1>